### ISSUE TITLE
UI Active on background states

### ISSUE THREAD

**Issue by KamiGrave** [ChilliWorks/ChilliSource#12]
I've just created a small menu system with a few buttons on it (labels with a function registered with the touch released event). Pressing on the buttons pushes a new state on top.

However, after I transition to the new states, whenever I tap where the menu buttons were the previous state's input events are still fired. Is this deliberate or is it a bug? My expected behaviour is that only the active UI canvas and widgets actually receive events.

**Comment by Chilli-Ian** [comment]
Hi KamiGrave,

This sounds like it could be a bug, yeah. If it's UI input events, this shouldn't be happening - they should only be fired for the active canvas. 

However, if your input events are coming directly from the PointerSystem, then this is the expected behaviour. The PointerSystem has no knowledge of `State`, so you'll need to manually add and remove your listener from the events during `OnResume()` and `OnSuspend()`.

I'll add a task to look into it.

Thank you,
 - Ian

**Comment by Chilli-Ian** [comment]
I've confirmed that this is an issue. A fix for it will be available soon :)

**Comment by Chilli-Ian** [comment]
Issue is fixed in CS v1.6.0
